---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
#  name:  {{ .Release.Name }}-{{ .Chart.Name }}
  name: {{ template "webui.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
 rules:
 - http:
     paths:
     - path: /*
       backend:
#         serviceName: {{ .Release.Name }}-{{ .Chart.Name }}
         serviceName: {{ template "webui.fullname" . }}
         servicePort: {{ .Values.service.externalPort }}

