---
apiVersion: v1
kind: Service
metadata:
#  name: {{ .Release.Name }}-{{ .Chart.Name }}
  name: {{ template "webui.fullname" . }}
  labels:
    app: search
    component: webui
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: search
    component: webui
    release: {{ .Release.Name }}
