---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "mongodb.fullname" . }}
  labels:
    app: reddit
    component: mongodb
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
       storage: 15Gi