---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab-ingress2
#  annotations:
#    kubernetes.io/ingress.allow-http: "true"
spec:
 rules:
 - http:
     paths:
     - path: /*
       backend:
         serviceName: gitlab-webservice
         servicePort: 8181

