---
apiVersion: apps/v1
kind: Deployment
metadata:
#  name: {{ .Release.Name }}-{{ .Chart.Name }}
  name: {{ template "webui.fullname" . }}
  labels:
    app: search
    component: webui
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
      component: webui
      release: {{ .Release.Name }}
  template:
    metadata:
      name: webui
      labels:
        app: search
        component: webui
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: webui
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: webui
          protocol: TCP
        env:
        - name: MONGO
          value: {{ .Values.mongodb.name | default (printf "%s-mongodb" .Release.Name) }}
        - name: MONGO_PORT
#          value: {{ .Values.mongodb.port }}
          value: "27017"
        - name: FLASK_APP
          value: {{ .Values.flaskapp.name }}
