crawler:
  service:
    externalPort: 80
    internalPort: 8000
  image:
    repository: hataldir/crawler
    tag: latest
  mongodb:
    port: "27017"
  rabbitmq:
    queue: queue
    user: user
    password: password
  crawler:
    interval: "60"
    urls: .*github.com

webui:
  service:
    externalPort: 80
    internalPort: 8000
  image:
    repository: hataldir/webui
    tag: latest
  mongodb:
    port: "27017"
  flaskapp:
    name: ui.py

mongodb:
  service:
    internalPort: 27017
    externalPort: 27017
  image:
    repository: mongo
    tag: 3.2

rabbitmq:
  service:
    internalPort: 5672
    externalPort: 5672
  image:
    repository: rabbitmq
    tag: 3
  user:
    name: user
    password: password
