service:
  externalPort: 80
  internalPort: 8080
image:
  repository: hataldir/crawler
  tag: latest
mongodb:
  port: "27017"
rabbitmq:
  queue: queue
  user: user
  password: password
crawler:
  interval: "60"
  urls: .*github.com
