---
apiVersion: apps/v1
kind: Deployment
metadata:
#  name: {{ .Release.Name }}-{{ .Chart.Name }}
  name: {{ template "crawler.fullname" . }}
  labels:
    app: search
    component: crawler
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
      component: crawler
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler
      labels:
        app: search
        component: crawler
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: crawler
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: crawler
          protocol: TCP
        env:
        - name: MONGO
          value: {{ .Values.mongodb.name | default (printf "%s-mongodb" .Release.Name) }}
        - name: MONGO_PORT
#          value: {{ .Values.mongodb.port }}
          value: "27017"
        - name: RMQ_HOST
          value: {{ .Values.rabbitmq.name | default (printf "%s-rabbitmq" .Release.Name) }}
        - name: RMQ_QUEUE
          value: {{ .Values.rabbitmq.queue }}
        - name: RMQ_USERNAME
          value: {{ .Values.rabbitmq.user }}
        - name: RMQ_PASSWORD
          value: {{ .Values.rabbitmq.password }}
        - name: CHECK_INTERVAL
#          value: {{ .Values.crawler.interval }}
          value: "60"
        - name: EXCLUDE_URLS
          value: {{ .Values.crawler.urls }}
