---
apiVersion: apps/v1
kind: Deployment
metadata:
#  name: {{ .Release.Name }}-{{ .Chart.Name }}
  name: {{ template "rabbitmq.fullname" . }}
  labels:
    app: reddit
    component: rabbitmq
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
      component: rabbitmq
      release: {{ .Release.Name }}
  template:
    metadata:
      name: rabbitmq
      labels:
        app: reddit
        component: rabbitmq
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: rabbitmq
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: rabbitmq
          protocol: TCP
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.user.name }}
        - name: RABBITMQ_DEFAULT_PASS
          value: {{ .Values.user.password }}
