---
apiVersion: v1
kind: Service
metadata:
#  name: {{ .Release.Name }}-{{ .Chart.Name }}
  name: {{ template "rabbitmq.fullname" . }}
  labels:
    app: reddit
    component: rabbitmq
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: reddit
    component: rabbitmq
    release: {{ .Release.Name }}
